#!/usr/bin/env python3
"""Build the self-hosted 京華老宋体 (KingHwa_OldSong) webfont chunks.

Charset  = GB2312 hanzi ∪ every char used under content/ ∪ CJK punctuation ∪ kana.
Chunking = hanzi sorted by frequency in content/, 30 per chunk, so a typical
article only pulls the top-ranked chunks; punctuation / kana / misc get their own.

Usage:
  python3 -m venv /tmp/fontenv && /tmp/fontenv/bin/pip install fonttools brotli
  /tmp/fontenv/bin/python scripts/split-kinghwa.py [/path/to/京華老宋体2.0.ttf]

Re-run after adding posts that use characters outside GB2312 (rare).
"""
import collections, glob, os, pathlib, subprocess, sys, tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/Library/Fonts/京華老宋体2.0.ttf"))
OUT_FONTS = ROOT / "themes/booooom/static/fonts/kinghwa"
OUT_CSS = ROOT / "themes/booooom/assets/css/kinghwa.css"
PYFTSUBSET = pathlib.Path(sys.executable).with_name("pyftsubset")
CHUNK = 30


def rng(a, b):
    return {chr(c) for c in range(a, b + 1)}


def is_han(c):
    o = ord(c)
    return 0x3400 <= o <= 0x9FFF or 0xF900 <= o <= 0xFAFF


def main():
    freq = collections.Counter()
    for f in glob.glob(str(ROOT / "content/**/*.md"), recursive=True):
        freq.update(open(f, encoding="utf-8", errors="ignore").read())
    for f in glob.glob(str(ROOT / "data/*.yaml")) + [str(ROOT / "hugo.yaml")]:
        freq.update(open(f, encoding="utf-8", errors="ignore").read())

    gb = set()
    for hi in range(0xB0, 0xF8):
        for lo in range(0xA1, 0xFF):
            try:
                gb.add(bytes([hi, lo]).decode("gb2312"))
            except UnicodeDecodeError:
                pass

    chars = set(freq) | gb | rng(0x20, 0x7E) | rng(0xA0, 0xFF) | rng(0x2000, 0x206F) | rng(0x3000, 0x303F) \
        | rng(0x3040, 0x30FF) | rng(0xFF00, 0xFFEF) | rng(0x2500, 0x257F) | rng(0x25A0, 0x25FF)
    chars = {c for c in chars if ord(c) >= 0x20 and not 0xD800 <= ord(c) <= 0xDFFF}

    base = [c for c in chars if not is_han(c)]
    punct = [c for c in base if 0x3000 <= ord(c) <= 0x303F or 0xFF00 <= ord(c) <= 0xFFEF or 0x2010 <= ord(c) <= 0x2027 or 0x2500 <= ord(c) <= 0x25FF]
    kana = [c for c in base if 0x3040 <= ord(c) <= 0x30FF]
    rest = [c for c in base if c not in set(punct) | set(kana)]
    han = sorted((c for c in chars if is_han(c)), key=lambda c: (-freq[c], ord(c)))
    chunks = [punct, kana, rest] + [han[i:i + CHUNK] for i in range(0, len(han), CHUNK)]

    # Pre-subset once to the full charset (much faster than subsetting the 45k-glyph source per chunk)
    with tempfile.TemporaryDirectory() as tmp:
        sub = pathlib.Path(tmp) / "sub.ttf"
        charfile = pathlib.Path(tmp) / "chars.txt"
        charfile.write_text("".join(sorted(chars)), encoding="utf-8")
        subprocess.run([PYFTSUBSET, SRC, f"--text-file={charfile}", "--layout-features=*", "--no-hinting",
                        "--desubroutinize", f"--output-file={sub}"], check=True)

        OUT_FONTS.mkdir(parents=True, exist_ok=True)
        for f in OUT_FONTS.glob("*.woff2"):
            f.unlink()
        css = ["/* 京華老宋体 (KingHwa_OldSong) v2.0 by TerryWang. Generated by scripts/split-kinghwa.py — do not edit. */"]
        total = 0
        for n, ch in enumerate(chunks):
            uni = ",".join(f"U+{ord(c):04X}" for c in ch)
            out = OUT_FONTS / f"kh-{n:03d}.woff2"
            subprocess.run([PYFTSUBSET, sub, f"--unicodes={uni}", "--flavor=woff2", "--layout-features=*",
                            "--no-hinting", "--desubroutinize", f"--output-file={out}"], check=True)
            total += out.stat().st_size
            css.append('@font-face{font-family:"KingHwa OldSong";font-style:normal;font-weight:400;font-display:swap;'
                       f'src:local("KingHwa_OldSong"),url("/fonts/kinghwa/{out.name}") format("woff2");unicode-range:{uni}}}')
        OUT_CSS.write_text("\n".join(css) + "\n", encoding="utf-8")
    print(f"{len(chunks)} chunks, {len(chars)} chars, {total // 1024} KB -> {OUT_FONTS}")


if __name__ == "__main__":
    main()
